version: "3.9"  # optional since v1.27.0
services:
  sql:
    build: SQL/.
    container_name: mssql
    restart: always
    ports:
      - "1433:1433" 
    volumes:
      - ./SQL/:/docker-entrypoint-initdb.d
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=A&VeryComplex123Password
  web_api:
    build: TagAPI/.
    depends_on:
      sql:
        condition: service_started
    container_name: tag-api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5001:8080"